services:
  - type: web
    name: jobfuture
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: CONTACT_TO_EMAIL
        value: info@jobkauppa.fi
      - key: CONTACT_FROM_EMAIL
        sync: false
      - key: RESEND_API_KEY
        sync: false
